import type {
  OrganizationalMetrics,
  DepartmentMetrics,
  SkillHeatmapData,
  AttritionRisk,
  StrategicInsight,
  WorkforceProjection,
} from "@/types/leadership"

export const mockOrganizationalMetrics: OrganizationalMetrics = {
  totalEmployees: 247,
  overallUtilization: 91,
  retentionRate: 94,
  skillsGrowth: 23,
  costSavings: 2400000,
  internalMobility: 18,
  timeToFill: 28,
  employeeSatisfaction: 85,
}

export const mockDepartmentMetrics: DepartmentMetrics[] = [
  {
    id: "1",
    name: "Engineering",
    headcount: 89,
    utilization: 94,
    avgPerformance: 87,
    retentionRate: 92,
    skillsGrowth: 28,
    budget: 12500000,
    budgetUtilization: 87,
    keySkills: ["React", "Python", "System Design", "AWS"],
    riskLevel: "low",
  },
  {
    id: "2",
    name: "Product",
    headcount: 34,
    utilization: 87,
    avgPerformance: 91,
    retentionRate: 96,
    skillsGrowth: 19,
    budget: 4200000,
    budgetUtilization: 92,
    keySkills: ["Product Strategy", "Analytics", "UX Design"],
    riskLevel: "low",
  },
  {
    id: "3",
    name: "Design",
    headcount: 21,
    utilization: 82,
    avgPerformance: 89,
    retentionRate: 88,
    skillsGrowth: 15,
    budget: 2800000,
    budgetUtilization: 78,
    keySkills: ["UI/UX", "Figma", "Design Systems"],
    riskLevel: "medium",
  },
  {
    id: "4",
    name: "Marketing",
    headcount: 28,
    utilization: 91,
    avgPerformance: 84,
    retentionRate: 89,
    skillsGrowth: 22,
    budget: 3500000,
    budgetUtilization: 95,
    keySkills: ["Digital Marketing", "Analytics", "Content"],
    riskLevel: "medium",
  },
  {
    id: "5",
    name: "Sales",
    headcount: 45,
    utilization: 96,
    avgPerformance: 92,
    retentionRate: 91,
    skillsGrowth: 12,
    budget: 6800000,
    budgetUtilization: 89,
    keySkills: ["Sales Strategy", "CRM", "Negotiation"],
    riskLevel: "low",
  },
  {
    id: "6",
    name: "Operations",
    headcount: 30,
    utilization: 88,
    avgPerformance: 86,
    retentionRate: 94,
    skillsGrowth: 18,
    budget: 3200000,
    budgetUtilization: 82,
    keySkills: ["Process Optimization", "Analytics", "Leadership"],
    riskLevel: "low",
  },
]

export const mockSkillHeatmap: SkillHeatmapData[] = [
  {
    skill: "Machine Learning",
    category: "AI/ML",
    currentSupply: 12,
    marketDemand: 95,
    internalDemand: 85,
    gap: -73,
    trend: "increasing",
    criticalityScore: 98,
  },
  {
    skill: "System Design",
    category: "Architecture",
    currentSupply: 23,
    marketDemand: 88,
    internalDemand: 92,
    gap: -65,
    trend: "increasing",
    criticalityScore: 95,
  },
  {
    skill: "Cloud Architecture",
    category: "Infrastructure",
    currentSupply: 34,
    marketDemand: 92,
    internalDemand: 78,
    gap: -44,
    trend: "stable",
    criticalityScore: 87,
  },
  {
    skill: "React",
    category: "Frontend",
    currentSupply: 67,
    marketDemand: 85,
    internalDemand: 72,
    gap: -5,
    trend: "stable",
    criticalityScore: 75,
  },
  {
    skill: "Python",
    category: "Programming",
    currentSupply: 45,
    marketDemand: 90,
    internalDemand: 68,
    gap: -23,
    trend: "increasing",
    criticalityScore: 82,
  },
  {
    skill: "Leadership",
    category: "Soft Skills",
    currentSupply: 28,
    marketDemand: 78,
    internalDemand: 85,
    gap: -50,
    trend: "stable",
    criticalityScore: 92,
  },
  {
    skill: "Data Science",
    category: "Analytics",
    currentSupply: 18,
    marketDemand: 87,
    internalDemand: 76,
    gap: -58,
    trend: "increasing",
    criticalityScore: 89,
  },
  {
    skill: "DevOps",
    category: "Infrastructure",
    currentSupply: 31,
    marketDemand: 83,
    internalDemand: 65,
    gap: -34,
    trend: "stable",
    criticalityScore: 78,
  },
]

export const mockAttritionRisks: AttritionRisk[] = [
  {
    employeeId: "3",
    employeeName: "Maria Rodriguez",
    department: "Engineering",
    role: "Full Stack Developer",
    riskScore: 85,
    riskFactors: ["Low utilization", "Declining performance", "Limited growth opportunities"],
    suggestedActions: ["Career development discussion", "Assign challenging project", "Mentorship program"],
    timeframe: "3-6 months",
    impactLevel: "high",
  },
  {
    employeeId: "7",
    employeeName: "James Wilson",
    department: "Design",
    role: "Senior Designer",
    riskScore: 72,
    riskFactors: ["Market salary gap", "Limited promotion path", "Team conflicts"],
    suggestedActions: ["Salary review", "Leadership training", "Team restructuring"],
    timeframe: "6-12 months",
    impactLevel: "medium",
  },
  {
    employeeId: "12",
    employeeName: "Lisa Chen",
    department: "Marketing",
    role: "Marketing Manager",
    riskScore: 68,
    riskFactors: ["Work-life balance", "Skill stagnation", "Limited autonomy"],
    suggestedActions: ["Flexible work arrangement", "Skill development budget", "Increased responsibility"],
    timeframe: "6-12 months",
    impactLevel: "medium",
  },
]

export const mockStrategicInsights: StrategicInsight[] = [
  {
    id: "1",
    type: "opportunity",
    priority: "high",
    title: "AI Skills Investment Opportunity",
    description:
      "73% skill gap in Machine Learning presents opportunity for competitive advantage through strategic upskilling",
    impact: "Could accelerate product innovation by 40% and reduce external hiring costs by $1.2M annually",
    suggestedActions: [
      "Launch ML certification program for 15 engineers",
      "Partner with university for advanced AI training",
      "Hire 2 ML specialists as internal trainers",
    ],
    affectedDepartments: ["Engineering", "Product"],
    timeline: "6-12 months",
    roi: 320,
    createdAt: new Date("2024-01-20"),
  },
  {
    id: "2",
    type: "risk",
    priority: "critical",
    title: "Leadership Pipeline Gap",
    description: "50% of current leaders eligible for retirement in 3 years with insufficient succession planning",
    impact: "Risk of knowledge loss and leadership vacuum affecting 120+ employees",
    suggestedActions: [
      "Identify high-potential employees for leadership track",
      "Implement mentorship program",
      "Create leadership development curriculum",
    ],
    affectedDepartments: ["All"],
    timeline: "Immediate - 18 months",
    roi: 180,
    createdAt: new Date("2024-01-18"),
  },
  {
    id: "3",
    type: "trend",
    priority: "medium",
    title: "Remote Work Skills Demand",
    description: "25% increase in demand for remote collaboration and digital communication skills",
    impact: "Teams with strong remote skills show 15% higher productivity and satisfaction",
    suggestedActions: [
      "Invest in collaboration tools training",
      "Develop remote leadership capabilities",
      "Create digital-first processes",
    ],
    affectedDepartments: ["All"],
    timeline: "3-6 months",
    roi: 145,
    createdAt: new Date("2024-01-22"),
  },
]

export const mockWorkforceProjections: WorkforceProjection[] = [
  {
    period: "Q2 2024",
    totalHeadcount: 267,
    projectedHires: 25,
    projectedAttrition: 5,
    skillsNeeded: ["Machine Learning", "System Design", "Product Management"],
    budgetImpact: 3200000,
  },
  {
    period: "Q3 2024",
    totalHeadcount: 285,
    projectedHires: 22,
    projectedAttrition: 4,
    skillsNeeded: ["Cloud Architecture", "Data Science", "Leadership"],
    budgetImpact: 2800000,
  },
  {
    period: "Q4 2024",
    totalHeadcount: 298,
    projectedHires: 18,
    projectedAttrition: 5,
    skillsNeeded: ["AI/ML", "DevOps", "UX Design"],
    budgetImpact: 2400000,
  },
  {
    period: "Q1 2025",
    totalHeadcount: 312,
    projectedHires: 20,
    projectedAttrition: 6,
    skillsNeeded: ["Blockchain", "Cybersecurity", "Mobile Development"],
    budgetImpact: 2600000,
  },
]
