import type { TeamMember, TalentMatch, ResourceAlert, ProjectStaffing, SkillGap } from "@/types/manager"

export const mockTeamMembers: TeamMember[] = [
  {
    id: "1",
    name: "Sarah Johnson",
    email: "sarah.johnson@company.com",
    role: "Senior Frontend Developer",
    department: "Engineering",
    skills: ["React", "TypeScript", "Next.js", "GraphQL", "UI/UX"],
    utilization: 65,
    availability: "partial",
    currentProjects: ["E-commerce Platform", "Design System"],
    performanceScore: 92,
    riskLevel: "low",
    avatar: "/professional-woman-diverse.png",
    joinDate: new Date("2022-03-15"),
    lastActive: new Date(),
  },
  {
    id: "2",
    name: "Alex Kim",
    email: "alex.kim@company.com",
    role: "DevOps Engineer",
    department: "Infrastructure",
    skills: ["AWS", "Docker", "Kubernetes", "Terraform", "Python"],
    utilization: 95,
    availability: "busy",
    currentProjects: ["Cloud Migration", "CI/CD Pipeline"],
    performanceScore: 88,
    riskLevel: "medium",
    avatar: "/professional-man.jpg",
    joinDate: new Date("2021-08-20"),
    lastActive: new Date(),
  },
  {
    id: "3",
    name: "Maria Rodriguez",
    email: "maria.rodriguez@company.com",
    role: "Full Stack Developer",
    department: "Engineering",
    skills: ["Python", "Django", "React", "PostgreSQL", "Machine Learning"],
    utilization: 45,
    availability: "available",
    currentProjects: ["Data Analytics Dashboard"],
    performanceScore: 85,
    riskLevel: "high",
    avatar: "/executive-woman.png",
    joinDate: new Date("2023-01-10"),
    lastActive: new Date(),
  },
  {
    id: "4",
    name: "David Chen",
    email: "david.chen@company.com",
    role: "Backend Developer",
    department: "Engineering",
    skills: ["Node.js", "Express", "MongoDB", "Redis", "Microservices"],
    utilization: 80,
    availability: "partial",
    currentProjects: ["API Gateway", "User Service"],
    performanceScore: 90,
    riskLevel: "low",
    avatar: "/professional-man.jpg",
    joinDate: new Date("2022-11-05"),
    lastActive: new Date(),
  },
  {
    id: "5",
    name: "Emily Zhang",
    email: "emily.zhang@company.com",
    role: "Mobile Developer",
    department: "Engineering",
    skills: ["React Native", "Swift", "Kotlin", "Firebase", "App Store"],
    utilization: 30,
    availability: "available",
    currentProjects: [],
    performanceScore: 87,
    riskLevel: "medium",
    avatar: "/professional-woman-diverse.png",
    joinDate: new Date("2023-06-12"),
    lastActive: new Date(),
  },
]

export const mockTalentMatches: TalentMatch[] = [
  {
    employee: mockTeamMembers[0],
    matchPercentage: 95,
    matchingSkills: ["React", "TypeScript", "Next.js"],
    missingSkills: ["Node.js"],
    availabilityScore: 65,
    recommendationReason: "Perfect skill match with strong frontend expertise and partial availability",
  },
  {
    employee: mockTeamMembers[2],
    matchPercentage: 88,
    matchingSkills: ["Python", "React", "Machine Learning"],
    missingSkills: ["System Design"],
    availabilityScore: 90,
    recommendationReason: "Strong technical skills with high availability and ML expertise",
  },
  {
    employee: mockTeamMembers[4],
    matchPercentage: 72,
    matchingSkills: ["React Native", "Firebase"],
    missingSkills: ["Backend Development", "System Design"],
    availabilityScore: 95,
    recommendationReason: "Mobile expertise with excellent availability, needs backend training",
  },
]

export const mockResourceAlerts: ResourceAlert[] = [
  {
    id: "1",
    type: "underutilized",
    severity: "medium",
    title: "Underutilized Talent Detected",
    description: "Emily Zhang has been at 30% utilization for 3 weeks",
    affectedEmployees: ["5"],
    suggestedAction: "Assign to Mobile App Redesign project or cross-train in web development",
    createdAt: new Date("2024-01-20"),
    resolved: false,
  },
  {
    id: "2",
    type: "overutilized",
    severity: "high",
    title: "Burnout Risk Alert",
    description: "Alex Kim has been at 95%+ utilization for 6 weeks",
    affectedEmployees: ["2"],
    suggestedAction: "Redistribute workload or hire additional DevOps engineer",
    createdAt: new Date("2024-01-18"),
    resolved: false,
  },
  {
    id: "3",
    type: "attrition-risk",
    severity: "critical",
    title: "High Attrition Risk",
    description: "Maria Rodriguez shows signs of disengagement - low utilization and declining performance",
    affectedEmployees: ["3"],
    suggestedAction: "Schedule 1:1 meeting to discuss career goals and project preferences",
    createdAt: new Date("2024-01-15"),
    resolved: false,
  },
  {
    id: "4",
    type: "skill-gap",
    severity: "medium",
    title: "Critical Skill Gap",
    description: "No team members have advanced System Design skills for upcoming architecture project",
    affectedEmployees: [],
    suggestedAction: "Enroll 2-3 senior developers in System Design training program",
    createdAt: new Date("2024-01-22"),
    resolved: false,
  },
  {
    id: "5",
    type: "opportunity",
    severity: "low",
    title: "Internal Mobility Opportunity",
    description: "Sarah Johnson ready for Tech Lead promotion based on performance and skills",
    affectedEmployees: ["1"],
    suggestedAction: "Discuss Tech Lead role and provide leadership training",
    createdAt: new Date("2024-01-19"),
    resolved: false,
  },
]

export const mockProjectStaffing: ProjectStaffing[] = [
  {
    id: "1",
    projectName: "AI-Powered Analytics Platform",
    requiredSkills: ["Python", "Machine Learning", "React", "System Design"],
    requiredHeadcount: 4,
    currentHeadcount: 2,
    priority: "high",
    startDate: new Date("2024-02-01"),
    endDate: new Date("2024-08-01"),
    status: "staffing",
    budget: 800000,
  },
  {
    id: "2",
    projectName: "Mobile App Redesign",
    requiredSkills: ["React Native", "UI/UX", "Firebase", "App Store"],
    requiredHeadcount: 3,
    currentHeadcount: 1,
    priority: "medium",
    startDate: new Date("2024-03-01"),
    endDate: new Date("2024-06-01"),
    status: "planning",
    budget: 450000,
  },
  {
    id: "3",
    projectName: "Cloud Infrastructure Upgrade",
    requiredSkills: ["AWS", "Kubernetes", "Terraform", "DevOps"],
    requiredHeadcount: 2,
    currentHeadcount: 2,
    priority: "critical",
    startDate: new Date("2024-01-15"),
    endDate: new Date("2024-04-15"),
    status: "in-progress",
    budget: 600000,
  },
]

export const mockSkillGaps: SkillGap[] = [
  {
    skill: "System Design",
    currentLevel: 2,
    requiredLevel: 8,
    gap: 6,
    affectedProjects: ["AI-Powered Analytics Platform"],
    suggestedEmployees: ["1", "4"],
  },
  {
    skill: "Machine Learning",
    currentLevel: 3,
    requiredLevel: 7,
    gap: 4,
    affectedProjects: ["AI-Powered Analytics Platform"],
    suggestedEmployees: ["3"],
  },
  {
    skill: "UI/UX Design",
    currentLevel: 4,
    requiredLevel: 7,
    gap: 3,
    affectedProjects: ["Mobile App Redesign"],
    suggestedEmployees: ["1", "5"],
  },
]
